<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_character',
		'title' => 'Character',
		'fields' => array (
			array (
				'key' => 'field_59287033e8cea',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_592870c3e8ceb',
				'label' => 'Name',
				'name' => 'character-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'What is this character\'s full name?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592871b4e8cec',
				'label' => 'Role',
				'name' => 'character-role',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s role in your story?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592871fce8ced',
				'label' => 'Other Names',
				'name' => 'character-other-names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What other aliases does this character go by?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592872bfe8cee',
				'label' => 'Gender',
				'name' => 'character-gender',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s gender',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287308e8cef',
				'label' => 'Age',
				'name' => 'character-age',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How old is this character?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928733ae8cf0',
				'label' => 'Universe',
				'name' => 'character-universe',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_592876199b880',
				'label' => 'Looks',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5928764d9b881',
				'label' => 'Weight',
				'name' => 'character-weight',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How much does this character weigh?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928767d9b882',
				'label' => 'Height',
				'name' => 'character-height',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How tall is this character?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928769b9b883',
				'label' => 'Hair Color',
				'name' => 'character-hair-color',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What color is this character\'s hair',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592876c99b884',
				'label' => 'Hair Style',
				'name' => 'character-hair-style',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How does this character style their hair?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592877029b885',
				'label' => 'Facial Hair',
				'name' => 'character-facial-hair',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What facial hair does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592877399b886',
				'label' => 'Eye Color',
				'name' => 'character-eye-color',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s eye color?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928789e9b887',
				'label' => 'Race',
				'name' => 'character-race',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592879969b888',
				'label' => 'Skin Tone',
				'name' => 'character-skin-tone',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What skin tone does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287a399b88a',
				'label' => 'Body Type',
				'name' => 'character-body-type',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s body type?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287a659b88b',
				'label' => 'Races',
				'name' => 'character-races-select',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'race',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287a969b88c',
				'label' => 'Nature',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287aa79b88d',
				'label' => 'Mannerisms',
				'name' => 'character-mannerisms',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What mannerisms does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287af39b88e',
				'label' => 'Motivations',
				'name' => 'character-motivations',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What motivates this character most?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287b129b88f',
				'label' => 'Flaws',
				'name' => 'character-flaws',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What flaws does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287b4b9b890',
				'label' => 'Prejudices',
				'name' => 'character-prejudices',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What prejudices does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287b7b9b891',
				'label' => 'Talents',
				'name' => 'character-talents',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What talents does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287b9f9b892',
				'label' => 'Hobbies',
				'name' => 'character-hobbies',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What hobbies does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287bb89b893',
				'label' => 'Personality type',
				'name' => 'character-personality-type',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287bdc9b894',
				'label' => 'Social',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287be89b895',
				'label' => 'Spoken Languages',
				'name' => 'character-spoken-languages',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'language',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287c4c9b896',
				'label' => 'Best Friends',
				'name' => 'character-best-friends',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287c999b897',
				'label' => 'Archenemies',
				'name' => 'character-archenemies',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287cee9b898',
				'label' => 'Religion',
				'name' => 'character-religion',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'religion',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_59287d1f9b899',
				'label' => 'Politics',
				'name' => 'character-politics',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What politics does this character have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287e039b89a',
				'label' => 'Occupation',
				'name' => 'occupation',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s occupation?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287e4b9b89b',
				'label' => 'Color',
				'name' => 'character-color',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s favorite color?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592ecfe94c00e',
				'label' => 'Food',
				'name' => 'character-food',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is the character\'s favorite food?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_592ed0014c00f',
				'label' => 'Possession',
				'name' => 'character-possession',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s favorite possession?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287e9a9b89c',
				'label' => 'Weapon',
				'name' => 'character-weapon',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s favorite weapon?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287eea9b89d',
				'label' => 'Animal',
				'name' => 'character-animal',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s favorite animal?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287f089b89e',
				'label' => 'History',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287f1c9b89f',
				'label' => 'Birthday',
				'name' => 'birthday',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'When is this character\'s birthday?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287f449b8a0',
				'label' => 'Birthplace',
				'name' => 'character-birthplace',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_59287f5f9b8a1',
				'label' => 'Education',
				'name' => 'character-education',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s level of education?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287f819b8a2',
				'label' => 'Background',
				'name' => 'character-background',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this character\'s background?',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287fa49b8a3',
				'label' => 'Family',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287fca9b8a4',
				'label' => 'Mothers',
				'name' => 'character-mothers',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287ff69b8a5',
				'label' => 'Fathers',
				'name' => 'character-fathers',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_592880169b8a6',
				'label' => 'Spouses',
				'name' => 'character-spouses',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5928802f9b8a7',
				'label' => 'Siblings',
				'name' => 'character-siblings',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_592880479b8a8',
				'label' => 'Children',
				'name' => 'character-children',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_592881079b8ab',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_592881169b8ac',
				'label' => 'Public Notes',
				'name' => 'character-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928815c9b8ad',
				'label' => 'Private Notes',
				'name' => 'character-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928805e9b8a9',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_592880699b8aa',
				'label' => 'Featured Image',
				'name' => 'character-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'character',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
