<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_group',
		'title' => 'Group',
		'fields' => array (
			array (
				'key' => 'field_5929ed932231a',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ed9a2231b',
				'label' => 'Name',
				'name' => 'group-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'What is the name of this group?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929edbf2231c',
				'label' => 'Description',
				'name' => 'group-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How would u describe this group?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929edd32231d',
				'label' => 'Other Names',
				'name' => 'group-other-names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What other names is this group known by?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929edee2231e',
				'label' => 'Universe',
				'name' => 'group-universe',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5929ee032231f',
				'label' => 'Heirarchy',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ee1022320',
				'label' => 'Organizational Structure',
				'name' => 'group-organizational-structure',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ee2e22321',
				'label' => 'Leaders',
				'name' => 'group-leaders',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ee4522322',
				'label' => 'Members',
				'name' => 'group-members',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ee6622323',
				'label' => 'Supergroups',
				'name' => 'group-supergroups',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ee7f22324',
				'label' => 'Subgroups',
				'name' => 'group-subgroups',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ee9722325',
				'label' => 'Sistergroups',
				'name' => 'group-sistergroups',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929eeab22326',
				'label' => 'Locations',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f2af36eee',
				'label' => 'Locations',
				'name' => 'group-locations',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929eede22327',
				'label' => 'Headquarters',
				'name' => 'group-headquarters',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5929eef722328',
				'label' => 'Offices',
				'name' => 'group-offices',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ef1822329',
				'label' => 'Purpose',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ef252232a',
				'label' => 'Motivations',
				'name' => 'group-motivations',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What motivates this group?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ef3d2232b',
				'label' => 'Goals',
				'name' => 'group-goals',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is the primary goal of this group?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ef592232c',
				'label' => 'Obstacles',
				'name' => 'group-obstacles',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What obstacles stand in the way of this group?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ef712232d',
				'label' => 'Risks',
				'name' => 'group-risks',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What risks are on the line for this group?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ef882232e',
				'label' => 'Politics',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ef922232f',
				'label' => 'Allies',
				'name' => 'group-allies',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f00822330',
				'label' => 'Enemies',
				'name' => 'group-enemies',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f01d22331',
				'label' => 'Rivals',
				'name' => 'group-rivals',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f02e22332',
				'label' => 'Clients',
				'name' => 'group-clients',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f03f22333',
				'label' => 'Inventory',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f04e22334',
				'label' => 'Inventory',
				'name' => 'group-inventory',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kinds of items does this group keep in inventory?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f06a22335',
				'label' => 'Equipment',
				'name' => 'group-equipment',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'item',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f08a22336',
				'label' => 'Key Items',
				'name' => 'group-key-items',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'item',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f0ac22337',
				'label' => 'Suppliers',
				'name' => 'group-suppliers',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'group',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f0c422338',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f133cd297',
				'label' => 'Public Notes',
				'name' => 'group-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f159cd298',
				'label' => 'Private Notes',
				'name' => 'group-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f24fa8923',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f265a8924',
				'label' => 'Featured Image',
				'name' => 'group-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'group',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
