<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_item',
		'title' => 'Item',
		'fields' => array (
			array (
				'key' => 'field_5928773efe6f2',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287749fe6f3',
				'label' => 'Name',
				'name' => 'item-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'What is this item\'s full name?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928782cfe6f4',
				'label' => 'Item Type',
				'name' => 'item-type',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What type of item is this?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5928784cfe6f5',
				'label' => 'Description',
				'name' => 'item-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Describe this item.',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287890fe6f6',
				'label' => 'Universe',
				'name' => 'item-universe',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_592878dffe6f7',
				'label' => 'Looks',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_592878fefe6f8',
				'label' => 'Materials',
				'name' => 'item-materials',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this item made out of?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287918fe6f9',
				'label' => 'Weight',
				'name' => 'item-weight',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How much does this item weigh?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287931fe6fa',
				'label' => 'History',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287938fe6fb',
				'label' => 'Original Owners',
				'name' => 'item-original-owners',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287a1afe6fc',
				'label' => 'Past Owners',
				'name' => 'item-past-owners',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287a2dfe6fd',
				'label' => 'Current Owners',
				'name' => 'item-current-owners',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287a49fe6fe',
				'label' => 'Makers',
				'name' => 'item-makers',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_59287a5afe6ff',
				'label' => 'Creation Date',
				'name' => 'item-creation-date',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'When was this item created?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287a75fe700',
				'label' => 'Abilities',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287a80fe701',
				'label' => 'Magic',
				'name' => 'item-magic',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kind of magic does this item possess?',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287ae3fe704',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287af2fe705',
				'label' => 'Public Notes',
				'name' => 'item-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you\'d like!',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287b09fe706',
				'label' => 'Private Notes',
				'name' => 'item-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you\'d like!',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_59287a98fe702',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_59287aa0fe703',
				'label' => 'Featured Image',
				'name' => 'item-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'item',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
