<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_language',
		'title' => 'Language',
		'fields' => array (
			array (
				'key' => 'field_5929f35f884bf',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f37b884c0',
				'label' => 'Name',
				'name' => 'language-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'What is the name of this language?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f398884c1',
				'label' => 'Other Names',
				'name' => 'language-other-names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What other names is this language known by?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f3b5884c2',
				'label' => 'Universe',
				'name' => 'language-universe',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5929f3cb884c3',
				'label' => 'Info',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f3d9884c4',
				'label' => 'History',
				'name' => 'language-history',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is the history of this language?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f3f1884c5',
				'label' => 'Typology',
				'name' => 'language-typology',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f403884c6',
				'label' => 'Dialectical Information',
				'name' => 'language-dialectical-information',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f41f884c7',
				'label' => 'Register',
				'name' => 'language-register',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f443884c8',
				'label' => 'Phonology',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f44d884c9',
				'label' => 'Phonology',
				'name' => 'language-phonology',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f463884ca',
				'label' => 'Grammar',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f470884cb',
				'label' => 'Grammar',
				'name' => 'language-grammar',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f4c0884cc',
				'label' => 'Entities',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f561884cd',
				'label' => 'Numbers',
				'name' => 'language-numbers',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 8,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f5b5884ce',
				'label' => 'Quantifiers',
				'name' => 'language-quantifiers',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 8,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f5df884cf',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f5eb884d0',
				'label' => 'Public Notes',
				'name' => 'language-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f604884d1',
				'label' => 'Private Notes',
				'name' => 'language-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f623884d2',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f62a884d3',
				'label' => 'Featured Image',
				'name' => 'language-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'language',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
