<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_location',
		'title' => 'Location',
		'fields' => array (
			array (
				'key' => 'field_590f86d3c509d',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f86e9c509e',
				'label' => 'Name',
				'name' => 'location-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'What is the name of this location?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8711c509f',
				'label' => 'Type',
				'name' => 'location-type',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What type of location is this?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8726c50a0',
				'label' => 'Universe',
				'name' => 'location-universe',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_590f8750c50a2',
				'label' => 'Description',
				'name' => 'location-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you\'d like!',
				'maxlength' => '',
				'rows' => 10,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f876bc50a3',
				'label' => 'Culture',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f8775c50a4',
				'label' => 'Language',
				'name' => 'location-language',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What language is spoken in this location?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8808c50a5',
				'label' => 'Population',
				'name' => 'location-population',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this location\'s population?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8823c50a6',
				'label' => 'Currency',
				'name' => 'location-currency',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is the currency used at this location?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8840c50a7',
				'label' => 'Motto',
				'name' => 'location-motto',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is this location\'s motto?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f887dc50a8',
				'label' => 'Laws',
				'name' => 'location-laws',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What are the laws in this location?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8892c50a9',
				'label' => 'Sports',
				'name' => 'location-sports',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What sports are played in this location?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f88abc50aa',
				'label' => 'Leaders',
				'name' => 'location-leaders',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_590f88d4c50ab',
				'label' => 'Languages',
				'name' => 'location-languages-select',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_590f88f6c50ac',
				'label' => 'Cities',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f88ffc50ad',
				'label' => 'Capital City',
				'name' => 'location-capital',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_590f8927c50ae',
				'label' => 'Largest Cities',
				'name' => 'location-largest-cities',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_590f893dc50af',
				'label' => 'Notable Cities',
				'name' => 'location-notable-cities',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_590f8953c50b0',
				'label' => 'Geography',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f895ec50b1',
				'label' => 'Area',
				'name' => 'location-area',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kind of area is this location in?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8977c50b2',
				'label' => 'Crops',
				'name' => 'location-crops',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What crops grow in this area?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f898cc50b3',
				'label' => 'Located At',
				'name' => 'location-located-at',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Where is this location located?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f89a1c50b4',
				'label' => 'Climate',
				'name' => 'location-climate',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is the climate like in this location?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f89b9c50b5',
				'label' => 'History',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f89e6c50b7',
				'label' => 'Founding Date',
				'name' => 'location-founding-date',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'When was this location established?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f89c2c50b6',
				'label' => 'Founding Story',
				'name' => 'location-founding-story',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How was this location founded?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8a11c50b8',
				'label' => 'Notable Wars',
				'name' => 'location-notable-wars',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What notable wars has this location been involved in?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8a2bc50b9',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f8a39c50ba',
				'label' => 'Public Notes',
				'name' => 'location-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you\'d like!',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8a52c50bb',
				'label' => 'Private Notes',
				'name' => 'location-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you\'d like!',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590f8a5bc50bc',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590f8a63c50bd',
				'label' => 'Featured Image',
				'name' => 'location-featured',
				'type' => 'image',
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'location',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
