<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_race',
		'title' => 'Race',
		'fields' => array (
			array (
				'key' => 'field_5929e3973c73f',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e3a23c740',
				'label' => 'Name',
				'name' => 'race-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e4033c742',
				'label' => 'Other Names',
				'name' => 'race-other-names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What other names does this race have?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e4263c743',
				'label' => 'Universe',
				'name' => 'race-universe',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5929e3ca3c741',
				'label' => 'Description',
				'name' => 'race-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How would you describe the people of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e4603c744',
				'label' => 'Looks',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e4763c745',
				'label' => 'Body Shape',
				'name' => 'race-body-shape',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What does the average body shape look like?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e4993c746',
				'label' => 'Skin Colors',
				'name' => 'race-skin-colors',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What skin color(s) are common for this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e4c83c747',
				'label' => 'General Height',
				'name' => 'race-general-height',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How tall is this race on average?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e4e93c748',
				'label' => 'General Weight',
				'name' => 'race-general-weight',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How heavy is the average person of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e50d3c749',
				'label' => 'Notable Features',
				'name' => 'race-notable-features',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What physical features are most noticeable for this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e5323c74a',
				'label' => 'Physical Variance',
				'name' => 'race-physical-variance',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How much variance is there between individuals of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e5593c74b',
				'label' => 'Typical Clothing',
				'name' => 'race-typical-clothing',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kind of clothing is common with the individuals of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e5853c74c',
				'label' => 'Traits',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e5963c74d',
				'label' => 'Strengths',
				'name' => 'race-strengths',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What are the strengths of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e5ac3c74e',
				'label' => 'Weaknesses',
				'name' => 'race-weaknesses',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What are the weaknesses of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e5cd8e0f8',
				'label' => 'Culture',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e5d68e0f9',
				'label' => 'Famous Figures',
				'name' => 'race-famous-figures',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929e6308e0fa',
				'label' => 'Traditions',
				'name' => 'race-traditions',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What traditions are common with this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e65b8e0fb',
				'label' => 'Beliefs',
				'name' => 'race-beliefs',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What beliefs are commonly held by this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e6798e0fc',
				'label' => 'Governments',
				'name' => 'race-governments',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What governments are common with this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e6958e0fd',
				'label' => 'Technologies',
				'name' => 'race-technologies',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kinds of technologies does this race societies take advantage of?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e6dd8e0fe',
				'label' => 'Occupations',
				'name' => 'race-occupations',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What occupations are common with this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e75d8e0ff',
				'label' => 'Economics',
				'name' => 'race-economics',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What does the economic situation look like for this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e77c8e100',
				'label' => 'Favorite Foods',
				'name' => 'race-favorite-foods',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What are the most common favorite foods of this race?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e79d8e101',
				'label' => 'History',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e7af8e102',
				'label' => 'Notable Events',
				'name' => 'race-notable-events',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What events are most important to this race?',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e7f88e103',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e8048e104',
				'label' => 'Public Notes',
				'name' => 'race-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e8348e105',
				'label' => 'Private Notes',
				'name' => 'race-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e84f8e106',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e8598e107',
				'label' => 'Featured Image',
				'name' => 'race-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'race',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
