<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_religion',
		'title' => 'Religion',
		'fields' => array (
			array (
				'key' => 'field_5929e926838a4',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e936838a5',
				'label' => 'Name',
				'name' => 'religion-name',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What is the name of this religion?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e977838a7',
				'label' => 'Other Names',
				'name' => 'religion-other-names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What other names is the religion known by?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e98f838a8',
				'label' => 'Universe',
				'name' => 'religion-universe',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5929e964838a6',
				'label' => 'Description',
				'name' => 'religion-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How is this religion usually described?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e9a5838a9',
				'label' => 'History',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929e9b5838aa',
				'label' => 'Origin Story',
				'name' => 'religion-origin-story',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'How did this religion first come into existence?',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929e9d0838ab',
				'label' => 'Notable Figures',
				'name' => 'religion-notable-figures',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929e9ec838ac',
				'label' => 'Artifacts',
				'name' => 'religion-artifacts',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'item',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ea0d838ad',
				'label' => 'Beliefs',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ea17838ae',
				'label' => 'Deities',
				'name' => 'religion-deities',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ea8d838af',
				'label' => 'Teachings',
				'name' => 'religion-teachings',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What values does this religion teach?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929eaa4838b0',
				'label' => 'Prophecies',
				'name' => 'religion-prophecies',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What prophecies does this religion teach?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929eabb838b1',
				'label' => 'Places of Worship',
				'name' => 'religion-places-of-worship',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Where does this religion worship happen?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929eaec838b2',
				'label' => 'Worship Services',
				'name' => 'religion-worship-services',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kind of worship services are common with this religion?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ebaf838b3',
				'label' => 'Obligations',
				'name' => 'religion-obligations',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What kinds of obligations are required of those who practice this religion?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ebca838b4',
				'label' => 'Vision of Paradise',
				'name' => 'religion-vision-of-paradise',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What does this religion\'s vision of paradise look like?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ebf7838b5',
				'label' => 'Traditions',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ec03838b6',
				'label' => 'Initiation Process',
				'name' => 'religion-initiation-process',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What does this religions initiation process entail?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ec34838b7',
				'label' => 'Rituals',
				'name' => 'religion-rituals',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What rituals are common with this religion?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ec48838b8',
				'label' => 'Holidays',
				'name' => 'religion-holidays',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What are the religious holidays?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ec6a838b9',
				'label' => 'Spread',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ec75838ba',
				'label' => 'Locations',
				'name' => 'religion-locations',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929ec8d838bb',
				'label' => 'Races',
				'name' => 'religion-races',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'race',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f1f6e2d00',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929eca8838bc',
				'label' => 'Public Notes',
				'name' => 'religion-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 8,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ecc4838bd',
				'label' => 'Private Notes',
				'name' => 'religion-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929ecdb838be',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929ece4838bf',
				'label' => 'Featured Image',
				'name' => 'religion-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5929f1fee2d01',
				'label' => '',
				'name' => '',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'religion',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
