<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_scene',
		'title' => 'Scene',
		'fields' => array (
			array (
				'key' => 'field_5929f6f3d39e2',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f6fdd39e3',
				'label' => 'Name',
				'name' => 'scene-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'What is the name of this scene?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f717d39e4',
				'label' => 'Summary',
				'name' => 'scene-summary',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f734d39e5',
				'label' => 'Universe',
				'name' => 'scene-universe',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'universe',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5929f745d39e6',
				'label' => 'Members',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f74fd39e7',
				'label' => 'Characters',
				'name' => 'scene-characters',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'character',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f773d39e8',
				'label' => 'Locations',
				'name' => 'scene-locations',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'location',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f797d39e9',
				'label' => 'Items',
				'name' => 'scene-items',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'item',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_5929f7acd39ea',
				'label' => 'Action',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f7b6d39eb',
				'label' => 'Causation',
				'name' => 'scene-causation',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'What caused this to happen?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f7e5d39ec',
				'label' => 'Description',
				'name' => 'scene-description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f7f7d39ed',
				'label' => 'Results',
				'name' => 'scene-results',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f80ad39ee',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f818d39ef',
				'label' => 'Public Notes',
				'name' => 'scene-public',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f82dd39f0',
				'label' => 'Private Notes',
				'name' => 'scene-private',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5929f844d39f1',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5929f850d39f2',
				'label' => 'Featured Image',
				'name' => 'scene-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'scene',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
