<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_universe',
		'title' => 'Universe',
		'fields' => array (
			array (
				'key' => 'field_590cec9e5ba1a',
				'label' => 'Overview',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590cecb75ba1b',
				'label' => 'Name',
				'name' => 'universe-name',
				'type' => 'textarea',
				'required' => 1,
				'default_value' => 'What is the name of this universe?',
				'placeholder' => 'What is the name of this universe?',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590cecd85ba1d',
				'label' => 'Genre',
				'name' => 'universe-genre',
				'type' => 'textarea',
				'default_value' => 'Write as little or as much as you want!',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590cecc65ba1c',
				'label' => 'Description',
				'name' => 'universe-description',
				'type' => 'textarea',
				'default_value' => 'How would you describe this universe?',
				'placeholder' => 'How would you describe this universe?',
				'maxlength' => '',
				'rows' => 10,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590ced185ba1e',
				'label' => 'History',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590ced245ba1f',
				'label' => 'History',
				'name' => 'universe-history',
				'type' => 'textarea',
				'default_value' => 'Write as little or as much as you want!',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 10,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590ced4a5ba20',
				'label' => 'Rules',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590ced565ba21',
				'label' => 'Laws of Physics',
				'name' => 'universe-physics',
				'type' => 'textarea',
				'default_value' => 'What are the laws of physics like in this universe?',
				'placeholder' => 'What are the laws of physics like in this universe?',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590ced785ba22',
				'label' => 'Magic System',
				'name' => 'universe-magic',
				'type' => 'textarea',
				'default_value' => 'What is the magic system like in this universe?',
				'placeholder' => 'What is the magic system like in this universe?',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590ced955ba23',
				'label' => 'Technologies',
				'name' => 'universe-technologies',
				'type' => 'textarea',
				'default_value' => 'What is the level of technology in this universe?',
				'placeholder' => 'What is the level of technology in this universe?',
				'maxlength' => '',
				'rows' => 5,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590cedb35ba24',
				'label' => 'Notes',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590cedbf5ba25',
				'label' => 'Public Notes',
				'name' => 'universe-public',
				'type' => 'textarea',
				'default_value' => 'Write as little or as much as you want!',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 10,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590cede15ba26',
				'label' => 'Private Notes',
				'name' => 'universe-private',
				'type' => 'textarea',
				'default_value' => 'Write as little or as much as you want!',
				'placeholder' => 'Write as little or as much as you want!',
				'maxlength' => '',
				'rows' => 10,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_590cedef5ba27',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_590cedf75ba28',
				'label' => 'Gallery',
				'name' => 'universe-featured',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'universe',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
